apiVersion: v1
kind: Service
metadata:
  name: geth
  namespace: web3
spec:
  ports:
    - port: 8545
      name: http
    - port: 8551
      name: authrpc
    - port: 30303
      name: p2p
    - port: 6060
      name: metrics
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: geth
---
apiVersion: v1
kind: Service
metadata:
  name: prysm
  namespace: web3
spec:
  ports:
    - port: 3500
      name: http
    - port: 4000
      name: grpc
    - port: 8080
      name: metrics
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: prysm
---
apiVersion: v1
kind: Service
metadata:
  name: geth-rpc
  namespace: web3
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: 8545
      name: http
  selector:
    app: geth
